In [ ]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

print(df)



In [3]:
#1. Answer:
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'],errors='coerce')  # Error: Cannot convert 'Thirty' to int

print(df)

   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [ ]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value)  # Error: fillna() does not modify in place

print(df)


In [4]:
#2. Answer:
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value, inplace=True)  # Error: fillna() does not modify in place

print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
#3.from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)


In [5]:
#3. Answer:
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([[1], [2], [3], [4], [5]])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [ ]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


In [6]:
#4. Answer:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1,1)  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)


In [7]:
#5. Answer:
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [ ]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'])  # Error: Data should be reshaped
print(encoded)


In [8]:
#6. Answer:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])
print(encoded.toarray())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [9]:
#6. Answer:
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
#7.from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

model = LogisticRegression()
model.fit(X_train, y_train)


In [10]:
#7. Answer:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]

encode=LabelEncoder()
y_train_encoded=encode.fit_transform(y_train)

model = LogisticRegression()
model.fit(X_train, y_train_encoded)

LogisticRegression()

In [ ]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

model = LinearRegression()
model.fit(X_train, y_train)  


In [11]:
#8. Answer:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

simp_imp=SimpleImputer(strategy='mean')
X_train_pre=simp_imp.fit_transform(X_train)

model = LinearRegression()
model.fit(X_train_pre, y_train)

LinearRegression()

In [ ]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


In [12]:
#9. Answer:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]

encode=LabelEncoder()
y_train_encoded=encode.fit_transform(y_train)

model = DecisionTreeClassifier()
model.fit(X_train, y_train_encoded)

DecisionTreeClassifier()

In [ ]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


In [13]:
#10. Answer:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

scaler=StandardScaler()
X_train_scaler=scaler.fit_transform(X_train)

model = SVC()
model.fit(X_train_scaler, y_train)
predict_scaler=scaler.transform([[1, 150]])
print(model.predict(predict_scaler))

[0]
